-- INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('1', 'Card', '1485', '2022-02-10', '1', '1');
-- INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('2', 'Card', '7521', '2022-01-01', '2', '1');
-- INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('3', 'Cash', '5689', '2022-05-10', '3', '1');
-- INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('4', 'Cash', '2147', '2022-07-10', '4', '1');
-- INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('5', 'Card', '4785', '2022-04-03', '5', '1');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('6', 'Card', '1014', '2022-10-10', '6', '3');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('7', 'Card', '4851', '2022-12-10', '7', '3');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('8', 'Card', '5623', '2022-10-24', '8', '3');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('9', 'Card', '7412', '2022-10-03', '9', '3');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('10', 'Cash', '1269', '2022-04-4', '10', '3');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('11', 'Card', '4758', '2022-10-14', '11', '5');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('12', 'Cash', '1023', '2022-10-12', '12', '6');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('13', 'Card', '1035', '2022-04-10', '13', '6');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('14', 'Card', '1065', '2022-03-25', '14', '7');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('15', 'Card', '4503', '2022-10-15', '15', '7');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('16', 'Card', '1549', '2022-11-24', '16', '8');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('17', 'Cash', '1048', '2022-02-4', '17', '10');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('18', 'Card', '1024', '2022-07-12', '18', '10');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('19', 'Card', '1098', '2022-2-10', '19', '11');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('20', 'Card', '2045', '2022-05-25', '20', '11');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('21', 'Card', '4201', '2022-01-20', '21', '11');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('22', 'Cash', '7041', '2022-04-25', '22', '11');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('23', 'Card', '4015', '2022-03-10', '23', '12');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('24', 'Card', '2586', '2022-04-02', '24', '12');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('25', 'Card', '4269', '2022-03-08', '25', '13');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('26', 'Card', '4785', '2022-04-20', '26', '13');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('27', 'Card', '4780', '2022-06-25', '27', '14');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('28', 'Cash', '7956', '2022-07-29', '28', '15');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('29', 'Card', '7413', '2022-04-12', '29', '15');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('30', 'Card', '7026', '2022-10-27', '30', '15');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('31', 'Cash', '5023', '2022-10-14', '31', '16');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('32', 'Card', '4015', '2022-12-20', '32', '17');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('33', 'Card', '4103', '2022-10-04', '33', '18');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('34', 'Cash', '1038', '2022-11-10', '34', '18');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('35', 'Card', '4560', '2022-12-10', '35', '18');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('36', 'Card', '2022', '2022-01-09', '36', '18');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('37', 'Card', '1440', '2022-03-26', '37', '18');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('38', 'Card', '1586', '2022-05-24', '38', '19');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('39', 'Cash', '9874', '2022-05-17', '39', '18');
INSERT INTO `myshop`.`transaction` (`ID`, `TransactionType`, `TracingNumber`, `TransactionDate`, `FactorID`, `customerID`) VALUES ('40', 'Card', '4562', '2022-11-24', '40', '18');
